# Generated by Django 4.2.7 on 2025-09-23 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        help_text="ID of the user these preferences belong to",
                        unique=True,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user wants to receive email notifications",
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user wants to receive SMS notifications",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user wants to receive push notifications",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet hours (no notifications)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End of quiet hours (no notifications)",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's timezone for quiet hours",
                        max_length=50,
                    ),
                ),
                (
                    "max_emails_per_day",
                    models.PositiveIntegerField(
                        default=50, help_text="Maximum number of emails per day"
                    ),
                ),
                (
                    "max_sms_per_day",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum number of SMS per day"
                    ),
                ),
                (
                    "frequency_preference",
                    models.JSONField(
                        default=dict,
                        help_text="Frequency preferences per notification type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_preferences",
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="user_prefer_user_id_63441d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique template identifier",
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject or notification title",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Template body with variable placeholders like {{user_name}}"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        help_text="Type of notification this template is for",
                        max_length=20,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="Schema definition for template variables",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["type", "active"], name="notificatio_type_a33110_idx"
                    ),
                    models.Index(fields=["name"], name="notificatio_name_a67357_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "notification_quotas",
                "indexes": [
                    models.Index(
                        fields=["user_id", "date"],
                        name="notificatio_user_id_5809b3_idx",
                    ),
                    models.Index(fields=["date"], name="notificatio_date_73d619_idx"),
                ],
                "unique_together": {("user_id", "notification_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        help_text="ID of the user receiving the notification"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        help_text="Type of notification sent",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("retry", "Retry"),
                        ],
                        default="pending",
                        help_text="Current status of the notification",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level for processing",
                        max_length=10,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email address, phone number, or device token",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Rendered subject line",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("body", models.TextField(help_text="Rendered notification body")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was successfully sent",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if sending failed",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to retry sending this notification",
                        null=True,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        help_text="External provider's message ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata about the notification",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID to correlate related notifications",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template used for this notification",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="core.notificationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"],
                        name="notificatio_user_id_190e63_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="notificatio_status_e9dec3_idx",
                    ),
                    models.Index(
                        fields=["type", "status"], name="notificatio_type_c2a750_idx"
                    ),
                    models.Index(
                        fields=["status", "retry_count"],
                        name="notificatio_status_8f2656_idx",
                    ),
                    models.Index(
                        condition=models.Q(("status", "failed")),
                        fields=["next_retry_at"],
                        name="notification_failed_retry_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="notificatio_correla_5e75a4_idx"
                    ),
                ],
            },
        ),
    ]
